name: stats
dependencies:
  - gdal=2.3.2
  - cartopy=0.16.0
  - pip
  - pip:
    - numpy==1.16.4
    - matplotlib==3.0.3
    - scipy==1.2.1
    - setuptools==41.0.1
    - pyorbital==1.5.0
    - geographiclib==1.49
    - tifffile==2019.5.22
    - Pillow==6.0.0
    - python_dateutil==2.8.0
    - pytest
    - apscheduler
    - flask
